export const messages = [
    "I can't get enough of this game, it's amazing!",
    'This game is so addicting, I could play it all day.',
    "I don't know where the time goes when I'm playing this game.",
    'This game is a real time-sink, but in the best way possible.',
    "I'm completely hooked on this game, it's amazing.",
    "I don't think I've ever enjoyed a game this much before.",
    'This game is pure magic, I’m loving every minute of it.',
    'I could play this game for hours and not get bored.',
    'This game is a masterpiece, I’m in awe of it.',
    "I'm blown away by this game, it's incredible.",
    "I'm having so much fun playing this game, it's the best.",
    'This game is like crack, I can’t get enough of it.',
    "I'm completely absorbed in this game, it's fantastic.",
    'This game is so immersive, I feel like I’m really there.',
    "I'm loving every second of this game, it's amazing.",
    'I’m having a blast playing this game, it’s so much fun.',
    'This game is like nothing I’ve ever played before, it’s incredible.',
    "I'm addicted to this game, it's the best.",
    'This game is so well-crafted, I’m blown away by it.',
    "I've never been so engrossed in a game before, it's amazing.",
    'This game is a real gem, I’m so glad I found it.',
    'I’m completely lost in this game, it’s fantastic.',
    'This game is a work of art, I’m in love with it.',
    'I’m having the time of my life playing this game, it’s incredible.',
    'This game is like a dream come true, I can’t get enough of it.',
    'I’m thoroughly enjoying this game, it’s amazing.',
    'This game is a true masterpiece, I’m blown away by it.',
    'I’m having a blast exploring this game, it’s so much fun.',
    'This game is so well-designed, I’m in awe of it.',
    'I’m completely addicted to this game, it’s the best.',
    'This game is a real treat, I’m loving every moment of it.',
    'I’m completely absorbed in this game world, it’s fantastic.',
    'This game is a true marvel, I’m blown away by it.',
    'I’m having so much fun playing this game, it’s amazing.',
    'This game is like nothing I’ve ever experienced before, it’s incredible.',
    "I'm completely hooked on this game, it's the best thing ever.",
    'This game is a real masterpiece, I’m in love with it.',
    'I’m having a blast battling through this game, it’s so much fun.',
    'This game is so well-crafted, it’s amazing.',
    'I’m completely immersed in this game, it’s fantastic.',
    'This game is a true wonder, I’m blown away by it.',
    'I’m having a blast exploring this game world, it’s incredible.',
    'This game is like a drug, I can’t stop playing it.',
    "I'm completely addicted to this game, it's the best thing ever.",
    'This game is a real gem, I’m loving every moment of it.',
    'I’m completely absorbed in this game, it’s fantastic.',
    'This game is a true masterpiece, I’m in awe of it.',
    'I’m having so much fun playing this game, it’s amazing.',
    'This game is like nothing I’ve ever played before, it’s incredible.',
    "I'm completely hooked on this game, it's the best.",
];
